name: negociopro2
description: NegocioPro — Gestión inteligente para tu negocio. Por FinanPro Solutions.
publish_to: 'none'
version: 1.2.0+3

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.0
  sqflite: ^2.3.2
  path: ^1.9.0
  intl: ^0.19.0
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  pdf: ^3.11.1
  share_plus: ^9.0.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  connectivity_plus: ^6.0.3
  uuid: ^4.4.0
  package_info_plus: ^8.1.0
  url_launcher: ^6.3.0
  google_fonts: ^6.2.1
  fl_chart: ^0.68.0
  path_provider: ^2.1.0
  flutter_launcher_icons: ^0.13.1
  mobile_scanner: ^6.0.0
  print_bluetooth_thermal: ^1.2.3
  printing: ^5.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png.png"